### ISSUE TITLE
Support newrelic_rpm 8.0

### ISSUE THREAD

**Issue by mattbrictson** [RenoFi/newrelic-sidekiq-metrics#101]
Hello again! Similar to #99, will you be supporting `newrelic_rpm` 8.0+ soon? [Version 8.0.0 of the gem](https://rubygems.org/gems/newrelic_rpm/versions/8.0.0) was released on September 22, 2021.

**Comment by knapo** [comment]
Hey @mattbrictson! Yes, I'll test it against 8.0 and release new version early next week.

**Comment by knapo** [comment]
Done and released 🎉
