### ISSUE TITLE
Custom metrics are not proper in NewRelic

### ISSUE THREAD

**Issue by Rashmibalkur** [RenoFi/newrelic-sidekiq-metrics#104]
I am using newrelic_rpm version 7.0.0 and newrelic-sidekiq-metrics version 1.3.1.  I have enabled failed and dead size along with defaults. But in newrelic dashboard metrics are not showing properly, for all the metrics (count,average etc) like enqueued,deadsize,failedsize data are showing the same.

My configurations are as below,

In config/initializers/newrelic_sidekiq_metrics.rb
`NewrelicSidekiqMetrics.use(:enqueued, :retry_size, :dead_size, :failed)`

**Comment by knapo** [comment]
Please prepare a PR with a fix
