### ISSUE TITLE
Custom metric name

### ISSUE THREAD

**Issue by dineshgowda24** [RenoFi/newrelic-sidekiq-metrics#111]
**Describe the solution**
Can we send a custom prefix for metrics? I have a couple of Sidekiqs across multiple microservices. Currently, the metrics are prefixed with `Custom/Sidekiq/<metric>`. I want a way to send `Custom/Sidekiq/<service>/<metric>.`

When will this feature be done?
NA

**Describe the users**
Microservices with multiple sidekiq

**Additional context**
NA

**Designs**
NA

**Comment by knapo** [comment]
@dineshgowda24 it's an open source project, if you want an extra functionality, please prepare a PR with that
