### ISSUE TITLE
Can't upgrade to newrelic_rpm 7.0.0

### ISSUE THREAD

**Issue by mattbrictson** [RenoFi/newrelic-sidekiq-metrics#99]
**Describe the bug**

I would like to upgrade my app to `newrelic_rpm` 7.0.0, but `newrelic-sidekiq-metrics` does not allow it.

If I look at my `Gemfile.lock`, I see that `newrelic-sidekiq-metrics` only allows 6.x:

```
newrelic-sidekiq-metrics (1.2.0)
  newrelic_rpm (~> 6.14)
  sidekiq (~> 6.1)
```

**To Reproduce**

Create a `Gemfile` that contains `newrelic-sidekiq-metrics`.

```
$ bundle init
$ bundle add newrelic-sidekiq-metrics
```

Try to update to the latest version of `newrelic_rpm`:

```
$ bundle update newrelic_rpm
Resolving dependencies...
Using newrelic_rpm 6.15.0
Bundler attempted to update newrelic_rpm but its version stayed the same
```

**Expected behavior**

I expected to be able to use the latest version of `newrelic_rpm`: https://rubygems.org/gems/newrelic_rpm

**Comment by knapo** [comment]
@mattbrictson thanks for reporting, I updated `newrelic_rpm` dependency constraint and released a new version.

**Comment by mattbrictson** [comment]
Thanks! ❤️
